const seedEmployees=[{id:1,name:'김민지',team:'사례관리팀',role:'상담원',status:'재직'},{id:2,name:'박서준',team:'사업지원팀',role:'사무원',status:'재직'},{id:3,name:'이하은',team:'심리지원팀',role:'치료사',status:'재직'},{id:4,name:'최도윤',team:'사례관리팀',role:'상담원',status:'휴직'}];
const seedGoals=[{id:1,employeeId:1,title:'사례기록 기한 준수',category:'과정',weight:40,progress:82,due:'2026-08-31'},{id:2,employeeId:1,title:'고위험 사례 리스크 관리',category:'리스크',weight:60,progress:65,due:'2026-09-30'},{id:3,employeeId:2,title:'월별 정산 오류율 감소',category:'정확성',weight:50,progress:92,due:'2026-08-31'},{id:4,employeeId:3,title:'치료계획 이행 및 종결률',category:'성과',weight:100,progress:74,due:'2026-10-31'}];
const seedMeetings=[{id:1,employeeId:1,date:'2026-07-22',topic:'업무 우선순위 조정',summary:'고위험 사례 집중을 위해 일반 사례 기록 일정을 재조정함.',action:'7월 말까지 일정표 공유'},{id:2,employeeId:3,date:'2026-07-18',topic:'치료 중도탈락 예방',summary:'초기 안내와 보호자 연락 주기를 강화하기로 함.',action:'초기 안내문 개선안 작성'}];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}; const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let employees=load('pmv2_employees',seedEmployees),goals=load('pmv2_goals',seedGoals),meetings=load('pmv2_meetings',seedMeetings),page='dashboard',modalType='';
const navs=[['dashboard','대시보드','▦'],['goals','성과관리','◎'],['meetings','면담관리','▤'],['employees','직원관리','♟']];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function emp(id){return employees.find(e=>e.id==id)||{name:'미지정',team:'-'}}
function avgFor(id){const g=goals.filter(x=>x.employeeId==id);return g.length?Math.round(g.reduce((a,x)=>a+Number(x.progress),0)/g.length):0}
function renderNav(){ $('#nav').innerHTML=navs.map(n=>`<button data-page="${n[0]}" class="${page===n[0]?'active':''}"><i class="icon">${n[2]}</i>${n[1]}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;$('#sidebar').classList.remove('open');render()}) }
function render(){renderNav();$('#pageTitle').textContent=navs.find(n=>n[0]===page)[1]; const c=$('#content'); if(page==='dashboard')c.innerHTML=dashboard();if(page==='goals')c.innerHTML=goalsPage();if(page==='meetings')c.innerHTML=meetingsPage();if(page==='employees')c.innerHTML=employeesPage();bind()}
function dashboard(){const avg=goals.length?Math.round(goals.reduce((a,g)=>a+Number(g.progress),0)/goals.length):0,delayed=goals.filter(g=>g.progress<60).length,completed=goals.filter(g=>g.progress>=100).length;return `<div class="notice">현재 V2 시험판은 입력 내용을 이 브라우저에 저장합니다. 여러 직원이 함께 사용하려면 다음 단계에서 Supabase 연동이 필요합니다.</div><div class="metric-grid">${[['전체 직원',employees.length,'현재 등록된 직원','♟'],['평균 진행률',avg+'%','전체 KPI 기준','↗'],['주의 필요',delayed,'진행률 60% 미만','!'],['완료 목표',completed,'진행률 100%','✓']].map(x=>`<div class="metric"><div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div><div class="metric-icon">${x[3]}</div></div>`).join('')}</div><div class="two-col"><div class="panel"><div class="panel-head"><div><h2>직원별 진행 현황</h2><p>등록된 KPI 평균 진행률</p></div><button class="text-btn goto" data-target="goals">전체 보기 ›</button></div><div class="progress-list">${employees.map(e=>{let p=avgFor(e.id);return `<div class="progress-row"><div class="person"><div class="mini-avatar">${esc(e.name[0])}</div><div><b>${esc(e.name)}</b><span>${esc(e.team)} · ${esc(e.role)}</span></div></div><div class="bar-wrap"><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b></div></div>`}).join('')}</div></div><div class="panel"><div class="panel-head"><div><h2>최근 면담</h2><p>최근 등록된 1:1 기록</p></div><button class="text-btn goto" data-target="meetings">전체 보기 ›</button></div><div class="meeting-list">${meetings.slice(0,4).map(m=>`<div class="meeting-card"><div class="date-box"><b>${m.date.slice(8)}</b><span>${m.date.slice(5,7)}월</span></div><div><b>${esc(emp(m.employeeId).name)} · ${esc(m.topic)}</b><p>${esc(m.summary)}</p></div></div>`).join('')||'<div class="empty">면담 기록이 없습니다.</div>'}</div></div></div>`}
function goalsPage(){return `<div class="panel"><div class="toolbar"><div class="search">⌕<input id="searchGoal" placeholder="직원명, 목표명 검색"></div><button class="primary open-modal" data-type="goal">＋ 성과목표 추가</button></div><div class="table-wrap"><table><thead><tr><th>직원</th><th>성과목표</th><th>구분</th><th>가중치</th><th>진행률</th><th>기한</th><th></th></tr></thead><tbody id="goalRows">${goalRows(goals)}</tbody></table></div></div>`}
function goalRows(list){return list.map(g=>`<tr><td><b>${esc(emp(g.employeeId).name)}</b><small>${esc(emp(g.employeeId).team)}</small></td><td>${esc(g.title)}</td><td><span class="chip">${esc(g.category)}</span></td><td>${g.weight}%</td><td><div class="inline-progress"><div class="bar"><i style="width:${g.progress}%"></i></div><b>${g.progress}%</b></div></td><td>${g.due}</td><td><button class="delete" data-delete-goal="${g.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">등록된 성과목표가 없습니다.</td></tr>'}
function meetingsPage(){return `<div class="page-actions"><div><h2>1:1 면담 기록</h2><p>면담 결과와 후속 실행 항목을 관리합니다.</p></div><button class="primary open-modal" data-type="meeting">＋ 면담 기록 추가</button></div><div class="cards-grid">${meetings.map(m=>`<article class="record-card"><div class="record-top"><div class="person"><div class="mini-avatar">${esc(emp(m.employeeId).name[0])}</div><div><b>${esc(emp(m.employeeId).name)}</b><span>${esc(emp(m.employeeId).team)}</span></div></div><span class="date">▣ ${m.date}</span></div><h3>${esc(m.topic)}</h3><p>${esc(m.summary)}</p><div class="action-box"><b>후속 실행</b><span>${esc(m.action)}</span></div><button class="delete" data-delete-meeting="${m.id}">기록 삭제</button></article>`).join('')||'<div class="empty">등록된 면담 기록이 없습니다.</div>'}</div>`}
function employeesPage(){return `<div class="page-actions"><div><h2>직원 목록</h2><p>소속, 직무, 상태를 관리합니다.</p></div><button class="primary open-modal" data-type="employee">＋ 직원 추가</button></div><div class="cards-grid employee-grid">${employees.map(e=>{let p=avgFor(e.id),n=goals.filter(g=>g.employeeId==e.id).length;return `<article class="employee-card"><div class="large-avatar">${esc(e.name[0])}</div><h3>${esc(e.name)}</h3><p>${esc(e.team)}</p><span class="role">▣ ${esc(e.role)}</span><div class="employee-stat"><span>KPI ${n}개</span><b>${p}%</b></div><div class="bar"><i style="width:${p}%"></i></div><button class="delete" data-delete-employee="${e.id}">직원 삭제</button></article>`}).join('')}</div>`}
function bind(){document.querySelectorAll('.goto').forEach(b=>b.onclick=()=>{page=b.dataset.target;render()});document.querySelectorAll('.open-modal').forEach(b=>b.onclick=()=>openModal(b.dataset.type));document.querySelectorAll('[data-delete-goal]').forEach(b=>b.onclick=()=>{goals=goals.filter(x=>x.id!=b.dataset.deleteGoal);save('pmv2_goals',goals);render()});document.querySelectorAll('[data-delete-meeting]').forEach(b=>b.onclick=()=>{meetings=meetings.filter(x=>x.id!=b.dataset.deleteMeeting);save('pmv2_meetings',meetings);render()});document.querySelectorAll('[data-delete-employee]').forEach(b=>b.onclick=()=>{if(confirm('직원을 삭제하시겠습니까? 관련 성과와 면담 기록은 유지됩니다.')){employees=employees.filter(x=>x.id!=b.dataset.deleteEmployee);save('pmv2_employees',employees);render()}});const s=$('#searchGoal');if(s)s.oninput=()=>{$('#goalRows').innerHTML=goalRows(goals.filter(g=>(emp(g.employeeId).name+' '+g.title+' '+g.category).includes(s.value)))}}
function employeeOptions(){return employees.map(e=>`<option value="${e.id}">${esc(e.name)} · ${esc(e.team)}</option>`).join('')}
function openModal(type){modalType=type;$('#modalBackdrop').classList.remove('hidden');$('#modalTitle').textContent=type==='goal'?'성과목표 추가':type==='meeting'?'면담 기록 추가':'직원 추가';let h='';if(type==='goal')h=`<label>직원<select name="employeeId">${employeeOptions()}</select></label><label>성과목표<input name="title" required></label><div class="form-grid"><label>구분<select name="category"><option>과정</option><option>성과</option><option>리스크</option><option>정확성</option><option>협업</option></select></label><label>가중치<input name="weight" type="number" min="0" max="100" value="50"></label><label>진행률<input name="progress" type="number" min="0" max="100" value="0"></label><label>기한<input name="due" type="date" value="2026-12-31"></label></div>`;if(type==='meeting')h=`<label>직원<select name="employeeId">${employeeOptions()}</select></label><label>면담일<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>면담 주제<input name="topic" required></label><label>주요 내용<textarea name="summary" required></textarea></label><label>후속 실행<textarea name="action" required></textarea></label>`;if(type==='employee')h=`<label>이름<input name="name" required></label><label>소속 팀<input name="team" required></label><label>직무<select name="role"><option>상담원</option><option>치료사</option><option>사무원</option><option>팀장</option></select></label>`;$('#modalBody').innerHTML=h}
function closeModal(){$('#modalBackdrop').classList.add('hidden');$('#modalForm').reset()}
$('#modalClose').onclick=closeModal;$('#modalCancel').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#modalForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(modalType==='goal'){goals.push({...d,id:Date.now(),employeeId:+d.employeeId,weight:+d.weight,progress:+d.progress});save('pmv2_goals',goals)}if(modalType==='meeting'){meetings.unshift({...d,id:Date.now(),employeeId:+d.employeeId});save('pmv2_meetings',meetings)}if(modalType==='employee'){employees.push({...d,id:Date.now(),status:'재직'});save('pmv2_employees',employees)}closeModal();render()};
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#exportBtn').onclick=()=>{const rows=[['직원','팀','직무','성과목표','구분','가중치','진행률','기한'],...goals.map(g=>{let e=emp(g.employeeId);return[e.name,e.team,e.role,g.title,g.category,g.weight,g.progress,g.due]})];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='성과관리_'+new Date().toISOString().slice(0,10)+'.csv';a.click()};render();
